In [2]:
# load packages
import pandas as pd
import numpy as np

In [3]:
# load data
data = pd.read_csv(r'breast-cancer-wisconsin.txt',header=None,na_values='?')

In [15]:
data.head()

0   1   2   3   4   5     6   7   8   9   10
0  1000025   5   1   1   1   2   1.0   3   1   1   2
1  1002945   5   4   4   5   7  10.0   3   2   1   2
2  1015425   3   1   1   1   2   2.0   3   1   1   2
3  1016277   6   8   8   1   3   4.0   3   7   1   2
4  1017023   4   1   1   3   2   1.0   3   1   1   2

In [16]:
data.columns

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [25]:
# add column names
columns = ['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11']
data.columns = columns

In [18]:
data.head()

V1  V2  V3  V4  V5  V6    V7  V8  V9  V10  V11
0  1000025   5   1   1   1   2   1.0   3   1    1    2
1  1002945   5   4   4   5   7  10.0   3   2    1    2
2  1015425   3   1   1   1   2   2.0   3   1    1    2
3  1016277   6   8   8   1   3   4.0   3   7    1    2
4  1017023   4   1   1   3   2   1.0   3   1    1    2

In [19]:
# check missing values
data.isnull().sum()

V1      0
V2      0
V3      0
V4      0
V5      0
V6      0
V7     16
V8      0
V9      0
V10     0
V11     0
dtype: int64

In [21]:
# Rows with missing values
data[data.isnull().any(axis=1)]  # row -> 0, column -> 1

V1  V2  V3  V4  V5  V6  V7  V8  V9  V10  V11
23   1057013   8   4   5   1   2 NaN   7   3    1    4
40   1096800   6   6   6   9   6 NaN   7   8    1    2
139  1183246   1   1   1   1   1 NaN   2   1    1    2
145  1184840   1   1   3   1   2 NaN   2   1    1    2
158  1193683   1   1   2   1   3 NaN   1   1    1    2
164  1197510   5   1   1   1   2 NaN   3   1    1    2
235  1241232   3   1   4   1   2 NaN   3   1    1    2
249   169356   3   1   1   1   2 NaN   3   1    1    2
275   432809   3   1   3   1   2 NaN   2   1    1    2
292   563649   8   8   8   1   2 NaN   6  10    1    4
294   606140   1   1   1   1   2 NaN   2   1    1    2
297    61634   5   4   3   1   2 NaN   2   3    1    2
315   704168   4   6   5   6   7 NaN   4   9    1    2
321   733639   3   1   1   1   2 NaN   3   1    1    2
411  1238464   1   1   1   1   1 NaN   2   1    1    2
617  1057067   1   1   1   1   1 NaN   1   1    1    2

In [19]:
data['V11'] = data['V11'].map({4:1,2:0})

KeyError: 'V11'

In [23]:
data.head()

V1  V2  V3  V4  V5  V6    V7  V8  V9  V10  V11
0  1000025   5   1   1   1   2   1.0   3   1    1    0
1  1002945   5   4   4   5   7  10.0   3   2    1    0
2  1015425   3   1   1   1   2   2.0   3   1    1    0
3  1016277   6   8   8   1   3   4.0   3   7    1    0
4  1017023   4   1   1   3   2   1.0   3   1    1    0

In [24]:
data.tail()

V1  V2  V3  V4  V5  V6   V7  V8  V9  V10  V11
694  776715   3   1   1   1   3  2.0   1   1    1    0
695  841769   2   1   1   1   2  1.0   1   1    1    0
696  888820   5  10  10   3   7  3.0   8  10    2    1
697  897471   4   8   6   4   3  4.0  10   6    1    1
698  897471   4   8   8   5   4  5.0  10   4    1    1

In [25]:
data.sample(5)

V1  V2  V3  V4  V5  V6    V7  V8  V9  V10  V11
459  1267898   5   1   3   1   2   1.0   1   1    1    0
115  1173347   1   1   1   1   2   5.0   1   1    1    0
511  1299924   5   1   1   1   2   1.0   2   1    1    0
70   1121919   5   1   3   1   2   1.0   2   1    1    0
530   837480   7   4   4   3   4  10.0   6   9    1    1

In [ ]:
# lets explore wrangle function for defining number of steps

In [8]:
pip install scikit-learn


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [66]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.impute import  KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [29]:
data2 = data.copy()
# drop rows with missing values
data2 = data2.dropna()

In [31]:
# Drafting function to wrangle the data
X = data2.drop(columns = ['V1','V11'])
Y = data2['V11']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
model = LogisticRegression()
model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)
accuracy = accuracy_score(Y_test, Y_pred)
print(accuracy)

# create confusion matrix
pd.crosstab(Y_test, Y_pred, rownames=['Actual'], colnames=['Predicted'], margins=True)
# confusion_matrix(Y_test, Y_pred)

0.9560975609756097


Predicted    2   4  All
Actual                 
2          125   2  127
4            7  71   78
All        132  73  205

In [35]:
def myLogisticRegression(dt):
    X = dt.drop(columns = ['V1','V11'])
    Y = dt['V11']
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)
    model = LogisticRegression()
    model.fit(X_train, Y_train)
    Y_pred_train = model.predict(X_train)
    Y_pred_test = model.predict(X_test)
    accuracy_trainData = accuracy_score(Y_train, Y_pred_train)
    accuracy_testData = accuracy_score(Y_test, Y_pred)
    print(accuracy)

    # create confusion matrix
    print(pd.crosstab(Y_test, Y_pred, rownames=['Actual'], colnames=['Predicted'], margins=True))
    # confusion_matrix(Y_test, Y_pred)

In [36]:
# Strategy 1 : Removing rows with missing values
myLogisticRegression(data.dropna())

0.9560975609756097
Predicted    2   4  All
Actual                 
2          125   2  127
4            7  71   78
All        132  73  205


In [37]:
# Strategy 2 : Replacing missing values with mean
data3 = data.copy()
data3 = data3.fillna(data3.mean()) # Fill missing values with mean of the column
myLogisticRegression(data3)

0.9523809523809523
Predicted    2   4  All
Actual                 
2          141   2  143
4            8  59   67
All        149  61  210


In [44]:
# Strategy 2.1 : Replacing missing values with mean using simple imputer
imputer = SimpleImputer(strategy='mean')
data4 = data.copy()
data4[['V7']] = imputer.fit_transform(data4[['V7']])
myLogisticRegression(data4)

0.9523809523809523
Predicted    2   4  All
Actual                 
2          141   2  143
4            8  59   67
All        149  61  210


In [45]:
# Strategy 3 : Replacing missing values with median using simple imputer
data5 = data.copy()
imputer = SimpleImputer(strategy='median')
data5[['V7']] = imputer.fit_transform(data5[['V7']])
myLogisticRegression(data5)


0.9619047619047619
Predicted    2   4  All
Actual                 
2          141   2  143
4            6  61   67
All        147  63  210


In [46]:
# Strategy 4 : Replacing missing values with mode using simple imputer
imputer = SimpleImputer(strategy='most_frequent')
data6 = data.copy()
data6[['V7']] = imputer.fit_transform(data6[['V7']])
myLogisticRegression(data6)

0.9619047619047619
Predicted    2   4  All
Actual                 
2          141   2  143
4            6  61   67
All        147  63  210


In [48]:
# Strategy 5 : Replacing missing values with constant using simple imputer
imputer = SimpleImputer(strategy='constant', fill_value=1)
data7 = data.copy()
data7[['V7']] = imputer.fit_transform(data7[['V7']])
myLogisticRegression(data7)

0.9619047619047619
Predicted    2   4  All
Actual                 
2          141   2  143
4            6  61   67
All        147  63  210


In [50]:
# Strategy 6 : Replacing missing values with KNN
imputer = KNNImputer(n_neighbors=2)
data8 = data.copy()
data8[['V7']] = imputer.fit_transform(data8[['V7']])
myLogisticRegression(data8)

0.9523809523809523
Predicted    2   4  All
Actual                 
2          141   2  143
4            8  59   67
All        149  61  210


In [56]:
# Strategy 7 : Replacing missing values with linear regression wtih other predictors
data9 = data.copy()
train = data9[data9['V7'].notnull()]
test = data9[data9['V7'].isnull()]
print(train.shape) 
print(test.shape)
linReg = LinearRegression()
# model.fit(X,Y)
linReg.fit(train.drop(columns=['V7','V1','V11']),train['V7'])


(683, 11)
(16, 11)


LinearRegression()

In [57]:
predictions = linReg.predict(test.drop(columns=['V1','V7','V11']))

In [59]:
# Rounding predictions
predictions = np.round(predictions,0)
predictions

array([5., 8., 1., 2., 1., 2., 3., 2., 2., 6., 1., 2., 6., 2., 1., 1.])

In [60]:
data9.loc[data9['V7'].isnull(),'V7'] = predictions

In [61]:
# Check missing values
data9.isnull().sum()

V1     0
V2     0
V3     0
V4     0
V5     0
V6     0
V7     0
V8     0
V9     0
V10    0
V11    0
dtype: int64

In [62]:
myLogisticRegression(data9)

0.9523809523809523
Predicted    2   4  All
Actual                 
2          142   1  143
4            9  58   67
All        151  59  210


In [65]:
# Strategy 8 : Replacing missing values with linear regression with perturbation
data10 = data.copy()
train = data10[data10['V7'].notnull()]
test = data10[data10['V7'].isnull()]

print(train.shape)
print(test.shape)

linRegPer = LinearRegression()
# model.fit(X,Y)
linRegPer.fit(train.drop(columns = ['V1','V7','V11']), train['V7'])
predictions = linRegPer.predict(test.drop(columns = ['V1','V7','V11']))

# add perturbation to predictions
perturbed_predictions = predictions + np.random.normal(0,0.1,len(predictions))
print(perturbed_predictions)

# Rounding perturbed predictions 
rounded_predictions = np.round(perturbed_predictions,0)
print(rounded_predictions)

# if less than 1 replace with 1 
rounded_predictions[rounded_predictions<1] = 1

# if greater than 10 then replace with 10
rounded_predictions[rounded_predictions>10] = 10

data10.loc[data10['V7'].isnull(), 'V7'] = rounded_predictions
myLogisticRegression(data10)

(683, 11)
(16, 11)
[5.46177581 8.32335334 0.94694835 1.58549367 0.95946118 2.3028462
 2.9467593  1.74100321 2.05189115 5.87808165 1.00137871 2.50969072
 5.67826025 1.49729867 0.81834412 0.71131664]
[5. 8. 1. 2. 1. 2. 3. 2. 2. 6. 1. 3. 6. 1. 1. 1.]
0.9523809523809523
Predicted    2   4  All
Actual                 
2          142   1  143
4            9  58   67
All        151  59  210


In [63]:
np.random.normal(0,0.1,len(predictions))

array([-0.00952436,  0.0131593 , -0.01803341,  0.03517017,  0.05113813,
       -0.16597431,  0.09189921, -0.22998415,  0.11245648, -0.16035345,
        0.01008044, -0.02630371,  0.08362267,  0.00450957, -0.08012315,
       -0.04681001])

In [68]:
# Strategy 9 : Replacing missing values with MICE
data11 = data.copy()
imputer = IterativeImputer()
data11[['V7']] = imputer.fit_transform(data11[['V7']])
myLogisticRegression(data11)

0.9523809523809523
Predicted    2   4  All
Actual                 
2          141   2  143
4            8  59   67
All        149  61  210
