### Class Date 17/05/2024 ###

In [4]:
import os

In [5]:
os.getcwd() # get current working directory

'/Users/zadidahsan/Documents/Class-5'

In [20]:
os.chdir() # change current working directory

TypeError: chdir() missing required argument 'path' (pos 1)

In [15]:
file1 = open("names.txt","r") # find handler
# print(f.read())

In [11]:
file1.read()

'Albert Zammit\nBetsy Yates\n   Chi-Yen Xu    \nDevi Wagle\n  Edward Valentine\nFrances Unwin\nGraeme Trotter'

In [14]:
file1.readlines()

['Albert Zammit\n',
 'Betsy Yates\n',
 '   Chi-Yen Xu    \n',
 'Devi Wagle\n',
 '  Edward Valentine\n',
 'Frances Unwin\n',
 'Graeme Trotter']

In [18]:
file1.readline()

'   Chi-Yen Xu    \n'

### Other data structures ###

In [26]:
mylist1 = [1,3,8,3,9,"zadid"]

In [31]:
mylist1.append("apple")

In [32]:
mylist1

[1, 3, 8, 3, 9, 'zadid', 'apple', 'apple', 'apple']

In [23]:
type(mylist1)

list

In [24]:
mylist1.append("orange")

In [25]:
print(mylist1)

[1, 3, 8, 3, 9, 'zadid', 'orange']


In [27]:
mylist1[5]

'zadid'

In [28]:
len(mylist1)

7

In [29]:
listC = ["Fruit groups",
          ["protein",["meat","fish","egg","soy"]],
          ["carbohydrate",["sugar","starch"]],
          ["fat",["oil","lard","butter"]],
          ["drinks",["coffee","milk","corbonated"]]
        ]  # Embedded list -> lists within list 
# Embedded list can not be converted to a data frame because not same length - can be accessed through index

In [30]:
listC[0]

'Fruit groups'

In [31]:
listC[1]

['protein', ['meat', 'fish', 'egg', 'soy']]

In [32]:
listC[2]

['carbohydrate', ['sugar', 'starch']]

In [33]:
listC[2][0]

'carbohydrate'

In [34]:
listC[2][1]

['sugar', 'starch']

In [36]:
listC[2][1][0]

'sugar'

In [37]:
listC[2][1][1]

'starch'

In [38]:
listC[4]

['drinks', ['coffee', 'milk', 'corbonated']]

In [39]:
listC[4][1]

['coffee', 'milk', 'corbonated']

In [40]:
listC[4][1][0]

'coffee'

In [41]:
listC[4][1][2]

'corbonated'

In [42]:
# lists are mutable
mylist1

[1, 3, 8, 3, 9, 'zadid', 'orange']

In [43]:
mylist1[1]

3

In [44]:
mylist1[1] = 13

In [45]:
mylist1

[1, 13, 8, 3, 9, 'zadid', 'orange']

In [46]:
# String - array of characters - list and string are not same
# Strings are not mutable(not changable)
mystring1 = "pathetic"

In [47]:
# mystring1[0] = "n" will not work

TypeError: 'str' object does not support item assignment

#### Dictionary

In [4]:
mydictionary1 = {"a":1,"b":3,"c":8,"d":3,"e":9,"f":"zadid"} # key-value pair

In [5]:
mydictionary1["d"] # dictionary can be called by index, only key

3

In [6]:
mydictionary1["f"]

'zadid'

In [7]:
mydictionary2 = {
               'boat':"lots of fun",
               'wedding':"a form of ceremony",
               'eclair':"a cake long in shape but short in duration",
               'pink':"a yellow lake",
               'ynambu':"a very large tinamou"
            }

In [8]:
mydictionary2['pink']

'a yellow lake'

In [9]:
mydictionary2.keys()

dict_keys(['boat', 'wedding', 'eclair', 'pink', 'ynambu'])

In [10]:
mydictionary2.values()

dict_values(['lots of fun', 'a form of ceremony', 'a cake long in shape but short in duration', 'a yellow lake', 'a very large tinamou'])

In [35]:
type(sorted(mydictionary2.items())) # Sorting in dictionary - after sorting dict has become list

list

In [36]:
dict(sorted(mydictionary2.items()))

{'boat': 'lots of fun',
 'eclair': 'a cake long in shape but short in duration',
 'pink': 'a yellow lake',
 'wedding': 'a form of ceremony',
 'ynambu': 'a very large tinamou'}

In [11]:
fruitslist=["apple","banana","cherry","jackfruit","lichi","orange"]

In [16]:
fruitsdict = {"apple":[200,200],"banana":300,"cherry":400,"jackfruit":500,"lichi":600,"orange":700}

In [17]:
type(fruitsdict)

dict

In [14]:
fruitsdict["apple"]   # dictionary -> unstructured data structure -> very flexible

[200, 200]

In [21]:
fruitsset={"apple","banana","cherry","jackfruit","lichi","orange"}

In [22]:
type(fruitsset) # set -> 3rd type of data structure

set

In [23]:
fruitstuple=("apple","banana","cherry","jackfruit","lichi","orange")

In [24]:
type(fruitstuple)

tuple

In [ ]:
# list, dictionary, set, tuple
# mutable(those that can be changed) -> set, dictionary, set
# When add in list -> 'append' command
# immutable -> tuple
# Sorting can not be done in set
# Sorting concept is not in dictionary
# Duplicate items can be added in list but not in set

In [25]:
fruitstuple[1]="guava"

TypeError: 'tuple' object does not support item assignment

In [ ]:
# numpy -> numerical python

In [39]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 352.6 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.7/13.7 MB 1.8 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [49]:
import numpy as np

In [ ]:
# numpy works with own data structure -> numpy array

In [41]:
aList = [[1,2,5,6],[2,8,5,9],[4,7,8,2]]

In [42]:
print(aList)

[[1, 2, 5, 6], [2, 8, 5, 9], [4, 7, 8, 2]]


In [43]:
print(aList*2)

[[1, 2, 5, 6], [2, 8, 5, 9], [4, 7, 8, 2], [1, 2, 5, 6], [2, 8, 5, 9], [4, 7, 8, 2]]


In [50]:
aArray = np.array(aList)

In [47]:
print(aArray)

[[1 2 5 6]
 [2 8 5 9]
 [4 7 8 2]]


In [48]:
print(aArray*2)

[[ 2  4 10 12]
 [ 4 16 10 18]
 [ 8 14 16  4]]


In [ ]:
# numpy is a mathematical package -> works in matrix

In [51]:
pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 1.8 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [52]:
import pandas as pd

In [53]:
a1DList = [1,2,5,6,2,8,5,9,4,7,8,2]
print("aList:\n",a1DList)

aList:
 [1, 2, 5, 6, 2, 8, 5, 9, 4, 7, 8, 2]


In [54]:
a1Darray = np.array(a1DList)

In [56]:
print(a1Darray)

[1 2 5 6 2 8 5 9 4 7 8 2]


In [ ]:
# pandas -> mainly 2 data structures => series and data frame
# series -> 1 column / 1 dimensional

In [58]:
pd.Series(a1Darray) # converting to series -> index is added, vertically shown, adding data type

0     1
1     2
2     5
3     6
4     2
5     8
6     5
7     9
8     4
9     7
10    8
11    2
dtype: int64

In [60]:
myDict1 = {"a":1,"c":5,"d":9}

In [61]:
pd.Series(myDict1) # when converted from dictionary to series, keys are converted to indexes

a    1
c    5
d    9
dtype: int64

In [63]:
myList2 = [[1,2,5,6],[2,8,5,9],[4,7,8,2]] # Embedded list

In [66]:
myarray2 = np.array(myList2)
print(myarray2)

[[1 2 5 6]
 [2 8 5 9]
 [4 7 8 2]]


In [67]:
mydf2 = pd.DataFrame(myList2) # will create rows and columns

In [68]:
mydf2[1]

0    2
1    8
2    7
Name: 1, dtype: int64

In [69]:
mydf2[2:3]

0  1  2  3
2  4  7  8  2

In [70]:
mydf2[0:2]

0  1  2  3
0  1  2  5  6
1  2  8  5  9

In [71]:
mydf2.loc[1,0:2]

0    2
1    8
2    5
Name: 1, dtype: int64

### Now working on auto.csv

In [72]:
df = pd.read_csv("Auto.csv")
print(df.to_string())

      mpg  cylinders  displacement  horsepower  weight  acceleration  year  origin                                  name
0    18.0          8         307.0         130    3504          12.0    70       1             chevrolet chevelle malibu
1    15.0          8         350.0         165    3693          11.5    70       1                     buick skylark 320
2    18.0          8         318.0         150    3436          11.0    70       1                    plymouth satellite
3    16.0          8         304.0         150    3433          12.0    70       1                         amc rebel sst
4    17.0          8         302.0         140    3449          10.5    70       1                           ford torino
5    15.0          8         429.0         198    4341          10.0    70       1                      ford galaxie 500
6    14.0          8         454.0         220    4354           9.0    70       1                      chevrolet impala
7    14.0          8         440

In [73]:
type(df)

pandas.core.frame.DataFrame

In [74]:
# First couple of rows
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   
2  18.0          8         318.0         150    3436          11.0    70   
3  16.0          8         304.0         150    3433          12.0    70   
4  17.0          8         302.0         140    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [76]:
df.shape # 392 rows, 9 columns

(392, 9)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           392 non-null    float64
 1   cylinders     392 non-null    int64  
 2   displacement  392 non-null    float64
 3   horsepower    392 non-null    int64  
 4   weight        392 non-null    int64  
 5   acceleration  392 non-null    float64
 6   year          392 non-null    int64  
 7   origin        392 non-null    int64  
 8   name          392 non-null    object 
dtypes: float64(3), int64(5), object(1)
memory usage: 27.7+ KB


In [78]:
df.describe()

mpg   cylinders  displacement  horsepower       weight  \
count  392.000000  392.000000    392.000000  392.000000   392.000000   
mean    23.445918    5.471939    194.411990  104.469388  2977.584184   
std      7.805007    1.705783    104.644004   38.491160   849.402560   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.000000    4.000000    105.000000   75.000000  2225.250000   
50%     22.750000    4.000000    151.000000   93.500000  2803.500000   
75%     29.000000    8.000000    275.750000  126.000000  3614.750000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration        year      origin  
count    392.000000  392.000000  392.000000  
mean      15.541327   75.979592    1.576531  
std        2.758864    3.683737    0.805518  
min        8.000000   70.000000    1.000000  
25%       13.775000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.025000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

In [79]:
df['origin']

0      1
1      1
2      1
3      1
4      1
      ..
387    1
388    2
389    1
390    1
391    1
Name: origin, Length: 392, dtype: int64

In [81]:
df['origin'].unique()

array([1, 3, 2])

In [83]:
df['origin'].value_counts()

origin
1    245
3     79
2     68
Name: count, dtype: int64

In [87]:
df['origin'] = df['origin'].replace({1:"American",2:"European",3:"Japanese"})

In [88]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70   
1  15.0          8         350.0         165    3693          11.5    70   
2  18.0          8         318.0         150    3436          11.0    70   
3  16.0          8         304.0         150    3433          12.0    70   
4  17.0          8         302.0         140    3449          10.5    70   

     origin                       name  
0  American  chevrolet chevelle malibu  
1  American          buick skylark 320  
2  American         plymouth satellite  
3  American              amc rebel sst  
4  American                ford torino

In [90]:
df['origin'].value_counts()

origin
American    245
Japanese     79
European     68
Name: count, dtype: int64

In [82]:
df['year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])